# Simple trop configuration for individual developers
#
# This is a minimal configuration suitable for solo development work.
# Place this file at ~/.config/trop/config.toml

# Port allocation range (default: 49152-65535, the ephemeral port range)
# This configuration uses a smaller, more manageable range
port_range = [50000, 60000]

# Automatically exclude ports already in use by the system
# This prevents trop from allocating ports that are currently occupied
auto_exclude_occupied = true

# Specific ports to never allocate (empty by default)
# Add any ports you want to reserve for specific purposes
exclude = []

# Optional: Set log level for debugging
# Uncomment to enable verbose logging
# log_level = "debug"
