# Team configuration for shared development environments
#
# This configuration is designed for teams working on a shared development
# machine or using consistent port ranges across team members.
# Place this file at ~/.config/trop/config.toml

# Allocate from higher ranges to avoid conflicts with common dev ports
# This keeps trop ports well away from commonly used development ports
port_range = [52000, 62000]

# Exclude common development ports that team members might use
# These are typical defaults for popular frameworks and tools
exclude = [
    # Web frameworks
    3000,  # React/Next.js/Node.js default
    3001,  # Common React alternative
    4200,  # Angular default
    5000,  # Flask default
    5173,  # Vite default
    8000,  # Django/Python HTTP server default
    8080,  # Common HTTP alternative
    8888,  # Jupyter Notebook

    # Databases
    5432,  # PostgreSQL
    3306,  # MySQL
    27017, # MongoDB
    6379,  # Redis

    # Other common services
    9000,  # PHP-FPM
    9090,  # Prometheus
    3030,  # Grafana
]

# Auto-exclude to avoid conflicts with running services
# This is especially important in team environments where services
# may be running that you're not aware of
auto_exclude_occupied = true

# Optional: Enable debug logging for troubleshooting
# Uncomment when investigating port allocation issues
# log_level = "debug"
