name: Dependabot Auto-Merge

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  enable-auto-merge:
    if: >-
      ${{ github.actor == 'dependabot[bot]' &&
          github.event.pull_request.base.ref == 'develop' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
